### ISSUE TITLE
Customize clock item

### ISSUE THREAD

**Issue by kbsali** [mate-desktop/mate-indicator-applet#55]
#### Expected behaviour

I would like to display the date as well as the time.

#### Actual behaviour

I only have the time displayed and cannot find any options/settings to also show the date in the applet.

#### MATE general version

1.22

#### Package version

1.22.1

#### Linux Distribution

Ubuntu-Mate 19.10

**Comment by lukefromdc** [comment]
Right-click on the clock, click "preferences" in the menu that comes up. In the default "General" tab you can select 12 or 24 hour format, "show the date," "show seconds," "show week numbers in calendar," "show weather," and "show temperature"

**Comment by lukefromdc** [comment]
Ubuntu does offer "indicator-datetime"
https://packages.ubuntu.com/eoan/indicator-datetime
If you are using indicator-datetime and not the panel clock, it should be providing a menu item for preferences, which should include setting up the time/date display format. If it does not, that should be an issue in indicator-datetime itself, as indicators send their menu items to the indicator applet (or mate-panel's native SNI support). 

If you are using indicator-datetime and there is  supposed to be a preferences menu for it but it's not working (and especially if it does work with the indicator applet removed and org->mate->panel->general->enable-sni-support set to TRUE in dconf-editor), then we would have an issue with this package and I will reopen this

**Comment by kbsali** [comment]
I have indeed added the clock applet to displaythe date time, **but** on Ubuntu-Mate the indicator applet also includes the clock but does allow to update its preferences (or at least I could not find the option).
See my setup : 
![2020-03-03_21-37](https://user-images.githubusercontent.com/53676/75817500-7bff5f80-5d97-11ea-9d87-6a632251a873.png)

**Comment by lukefromdc** [comment]
That looks like a bug in Ubuntu's Indicator Applet Complete or more likely indicator-datetime, not this package and you should open an issue there so it can be resolved

**Comment by kbsali** [comment]
Perfect, thanks for your help! :)

**Comment by pfalcon** [comment]
> That looks like a bug in Ubuntu's Indicator Applet Complete

So, let's go over the situation again, using the screenshot in comment: https://github.com/mate-desktop/mate-indicator-applet/issues/55#issuecomment-594157936 : 

1. There's "MATE Indicator Applet Complete", which is **this** repository.
2. It forcibly shows time/clock indicator, without any means to disable or configure it.
3. It's a common sense that this is a bug in this repository, regardless of its status in Ubuntu.

I may very well believe that in Ubuntu UI (Unity, or how it's called these days), forcibly showing something in user's face without their ability to configure/disable it is a "feature". That's exactly the reason why we don't use Ubuntu Unity and use MATE instead. So please kindly help to users fix this **bug**, inherited from Ubuntu. (The fix can be as simple as just disabling that unconditional clock item in "Indicator Applet Complete", given that a user can get a fully configurable clock via another applet, named "Clock" (also on the screenshot above)).

**Comment by pfalcon** [comment]
OMG, this is the state of modern computing at its best:

To get rid of that ugly duplicated clock indicator, delete "Indicator Applet Complete", and use just "Indicator Applet" (without "Complete). They appear to be different exactly in that useless clock item.

To add/configure clock, again, use "Clock" applet.

**Comment by hugobuddel** [comment]
It seems that this problem might be fixed in [Ubuntu MATE 21.04](https://ubuntu-mate.org/blog/ubuntu-mate-hirsute-hippo-final-release/#mate-desktop-). Apparently MATE switched to Ayatana Indicators in 20.10 and that screenshot shows that an "Ayatana Indicators Settings" screen with "Date and Time" settings has been added to the Control Center in 21.04.

So it is probably easier to change how the default clock looks in MATE 21.04 and up, but I haven't actually verified this myself.

**Comment by hugobuddel** [comment]
Apparently the 'show-clock' setting has been removed though: https://github.com/AyatanaIndicators/ayatana-indicator-datetime/pull/17 , so the "Indicator Applet Complete" without clock + "Clock" seems to be no longer possible, but that is probably not problematic, since either "Indicator Applet Complete" with date, or "Indicator Applet" + "Clock" seems to make more sense. (It is not yet clear to me what the difference is between "Indicator Applet Complete" and "Indicator Applet" other than the datetime indicator though.)
